### ISSUE TITLE
Wrong upload and download speed measurement

### ISSUE THREAD

**Issue by saugatadatta** [danopstech/speedtest_exporter#46]
**Describe the bug**
I have configured the setup with available docker image and managed to pull the data from Prometheus, but the speedtest data looks odd, I have 100 MBPS up/down fiber connection, and with this the download speed is showing in between 40-67 Mbps and upload speed  only showing 600 to 800 Kbps. It looks like it is not generating the result properly, probably using old binary.

**Comment by saugatadatta** [comment]
If you are having same problem, please use this Fork. You have to build your docker image from this, and this will use latest version of speedtest-go from https://github.com/showwin/speedtest-go

https://github.com/olqs/speedtest_exporter

Note : If you are using Raspberry Pi 64 Bit, then you have to change ENV GOARCH=amd64 to ENV GOARCH=arm64 in Dockerfile.

This works fine, but still the internet speed test result are not 100% correct, and it is because of speedtest-go implementation.

Thanks for olqs for this update.
https://github.com/olqs

**Comment by Matho** [comment]
Hi

Thanks for your answer. I have tried the recommended repo and I see, that the speedtest always use the same speedtest server now, and the speeds are also higher. But not such as I expected.

I'm writing instructions for those, who are not familiar with Docker and need to rebuild that repo.

I have built the repo for arm64 (Raspberry PI 4) - you can use this link https://hub.docker.com/r/mathosk/speedtest_exporter/tags

## Instructions - if you want to use my arm64 rpi 4 docker image:
Do changes in locally fetched https://github.com/danopstech/starlink project

Turn off the starlink project
`sudo docker-compose down`

`vim docker-compose.yaml`

Rewrite the compose - use my prebuilded image:
```
  speedtest_exporter:
    image: "mathosk/speedtest_exporter:arm64_latest"
    #entrypoint: ["/speedtest_exporter", "-server_id", "11213", "-server_fallback"]
    restart: always
    ports:
      - "9092:9090"
```
Pull the new docker image
`sudo docker-compose pull`

Start the project
`sudo docker-compose up --remove-orphan`


## Instructions - if you want to rebuild the repo
Login to your raspberry pi

```
mkdir ~/docker-builds
cd ~/docker-builds
wget https://github.com/olqs/speedtest_exporter
cd speedtest_exporter
```

`vim Dockerfile`
If you are using Raspberry Pi 64 Bit, then you have to change ENV GOARCH=amd64 to ENV GOARCH=arm64 in Dockerfile.

Build the image
`sudo docker build --no-cache -t YOUR_DOCKER_HUB_USER/speedtest_exporter:arm64_latest .`

If you want to push the image to your Docker Hub account (optional), login 
`sudo docker login --username=YOUR_DOCKER_HUB_USER`

Note: you do not need to push the image to Docker Hub. You can use your locally builded image instead - skip this step in such a situation
`sudo docker push YOUR_DOCKER_HUB_USER/speedtest_exporter:arm64_latest`

Logout from Docker hub, only if you was logged in 
`sudo docker logout`

Do changes in locally fetched https://github.com/danopstech/starlink project, in `docker-compose.yaml`

Rewrite the docker-compose - use YOUR prebuilded image source - change YOUR_DOCKER_HUB_USER to the value you set for docker build step
```
  speedtest_exporter:
    image: "YOUR_DOCKER_HUB_USER/speedtest_exporter:arm64_latest"
    #entrypoint: ["/speedtest_exporter", "-server_id", "11213", "-server_fallback"]
    restart: always
    ports:
      - "9092:9090"
```
optional - you have the repo available locally already
`sudo docker-compose pull`

start the project
`sudo docker-compose up --remove-orphan`
