### ISSUE TITLE
Unable to scrape metrics from ARM64 image

### ISSUE THREAD

**Issue by jesusleung** [danopstech/speedtest_exporter#79]
**Describe the bug**
I installed the linux/arm64 image, and I cannot scrape /metrics.
When I issue `curl HTTP://localhost:9090/metrics`, I get back `curl: (52) Empty reply from server`. I have no issue with the x86 image. 

**To Reproduce**
This is what I have under Services in the docker-compose file
```
  speedtest:
    image: ghcr.io/danopstech/speedtest_exporter:latest
    platform: linux/arm64
    container_name: speedtest
    ports:
    - '9090:9090'
    command: -server_id 1928 -server_fallback
    restart: always
```

**Expected behavior**
Output of speed test results

**Additional context**
 - OS: linux/arm64
 - speedtest_exporter:latest
